# Generated by Django 4.2.3 on 2023-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
