# Generated by Django 4.2.3 on 2023-08-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animals',
            name='video1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animals',
            name='video2',
            field=models.TextField(blank=True),
        ),
    ]
